# fly.toml app configuration file generated for ceis-api on 2024-11-12T11:52:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ceis-api'
primary_region = 'scl'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = "2gb"
  cpus = 4
  cpu_kind = "shared"
  memory_mb = 2048

[http_service.http_options]
  idle_timeout = 270

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 0
  [services.concurrency]
    hard_limit = 200
    soft_limit = 100
    type = "connections"